# workflow name
name: release

# on events
on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { os: darwin, arch: amd64, tags: netcgo }
          - { os: darwin, arch: arm64, tags: netcgo }
          - { os: linux, arch: amd64, env: CGO_ENABLED=0 }
          - { os: linux, arch: arm64, env: CGO_ENABLED=0 }
          - { os: windows, arch: amd64, env: CGO_ENABLED=0 }
    steps:
      # step 1: checkout repository code
      - name: Checkout the repository
        uses: actions/checkout@v4

      # step 2: generate build files
      - name: Build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          project_path: "./cmd/${{ github.event.repository.name }}"
          goversion: "1.20"
          # ldflags: "-X 'main.Version=$PRODUCT_VERSION' -X 'main.Revision=$PRODUCT_REVISION' -X 'main.RevisionTime=$PRODUCT_REVISION_TIME"
          extra_files: LICENSE README.md

      # step 3: upload build-artifacts
      # - name: Upload build-artifacts
      #   uses: skx/github-action-publish-binaries@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     args: "./sftp-sync/out/*.zip"
